# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink:           "/:title"
#relative_permalinks: true

# Setup
title:               "Research Papers"
tagline:             "Read, Review, Research, Repeat"
description:         "Review and summaries of research papers in the broad field of Machine Learning"
url:                 "https://vbbphc.github.io"
baseurl:             "/lanyon"
paginate:            5

# About/contact
author:
  name:              Vaibhav Balloli
  url:               https://twitter.com/v_balloli
  email:             balloli.vb@gmail.com

# Custom vars
version:             1.0.0
