# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: :title
#relative_permalinks: true

# Setup
title:               "Research Papers"
tagline:             "Read, Review, Research, Repeat"
description:         "Review and summaries of research papers in the broad field of Machine Learning"
url:                 "https://vbbphc.github.io"
baseurl:             "/research-papers"
paginate:            10
plugins:             [jekyll-paginate]
twitter_username: v_balloli
github_username:  vbbphc
disqus_baseurl: "https://vbbphc.github.io/"
disqus_shortname: vaibhavballoli

markdown: Pandoc
# About/contact
author:
  name:              Vaibhav Balloli
  url:               https://twitter.com/v_balloli
  email:             balloli.vb@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-pandoc
  pandoc:
    extensions:
    - mathjax  

exclude:
  - "/vendor/"
    
social:
  - name: Twitter
    icon: twitter
    username: v_balloli
    url: https://twitter.com/v_balloli
    desc: 
    share: true
  
  - name: GitHub
    icon: github
    username: vbbphc
    url: https://github.com/vbbphc
    desc: 
    share: false
    
  - name: Linkedin
    icon: linkedin
    username: vaibhavballoli
    url: https://linkedin.com/in/vaibhavballoli
    desc: 
    share: true
    
defaults:
  -
    scope:
      path: ""
    values:
      author: "Vaibhav Balloli"
      
gems: [jekyll-paginate]
paginate_path: "page:num" 

excerpt_separator: <!--end_excerpt-->
  
